config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'astronauts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :astronauts, only: [:show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show]
  resources :astronauts, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astronaut.rb
class Astronaut < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_synopsis,
    against: [ :name],
    using: {
      tsearch: { prefix: true }
    }
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, :bio, :nationality, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :astronaut
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :astronauts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/astronauts_controller.rb
class AstronautsController < ApplicationController
  before_action :set_astronaut, only: [:show, :destroy]
  def index
    if params[:query].present?
      @astronauts = Astronaut.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @astronauts = Astronaut.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @astronaut = Astronaut.new
  end

  def create
    @astronaut = Astronaut.new(astronaut_params)
    @astronaut.user = current_user

    if @astronaut.save

      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @astronaut.destroy

    redirect_to root_path
  end

  private

  def set_astronaut
    @astronaut = Astronaut.find(params[:id])
  end

  def astronaut_params
    params.require(:astronaut).permit(:name, :bio, :nationality, :time_slot, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @astronaut = Astronaut.find(params[:astronaut_id])
    @booking = Booking.new(strong_params)
    @booking.user = current_user
    @booking.astronaut = @astronaut
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def strong_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/astronauts/index.html.erb
<div class="banner row" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wallup.net/wp-content/uploads/2016/01/211730-space-Earth.jpg);">
  <div class="container row">
    <div class="col-6">
    <h1>Astroapp</h1>
    <p>Connect with the space!</p>
       <div>
        <%= form_tag root_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for astronaut"
            %>
          <div class="position-relative">
            <%= submit_tag "Search", class: "btn btn-ghost position-absolute bottom-0 end-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <h1 class="text-center">Astronauts</h1>
</div>




<div class="cards container grid">
    <% @astronauts.each do |astronaut| %>
        <% if astronaut.photo.attached?  %>
          <%= link_to astronaut_path(astronaut) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path astronaut.photo.key, height: 330, crop: :fill, gravity: :face %>')"></div>
          <% end  %>
        <% else  %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.OrTvDaHqHaLr8GCNb25AngHaE8%26pid%3DApi&f=1')">Cool</div>
        <% end  %>
    <% end  %>
</div>

app/views/astronauts/new.html.erb
<div class="container d-flex form row">
  <div class="col-6">
    <h2>Join us and add a new astronaut!</h2>
    <p>Help us to create new experiences of exploring the outer space by expanding our astro family!</p>
    <img width="300" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F4.bp.blogspot.com%2F_kVBIKsx0ZqQ%2FS_hLb0xiZYI%2FAAAAAAAAF44%2FU06csaqii-s%2Fs400%2FMillie_Hughes-Fulford.jpg&f=1&nofb=1" alt="">
  </div>

  <div class="col-6">
    <h3>Let's Start!</h3>
      <%= simple_form_for [@astronaut] do |f| %>
        <%= f.input :name %>
        <%= f.input :bio %>
        <%= f.input :nationality %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Launch new astronaut", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/astronauts/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card row flex-row mt-3" style="width: 50rem;">
    <div class="col-lg-8 card-body">
      <div class="d-flex">
        <% if @astronaut.photo.attached?  %>
          <%= cl_image_tag @astronaut.photo.key, height: 300, width: 400, crop: :fill, gravity: :face %>
        <% else  %>
          <img  class="my-2" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.OrTvDaHqHaLr8GCNb25AngHaE8%26pid%3DApi&f=1" alt="">
        <% end  %>
        <div class="container position-relative d-flex justify-content-center ">
          <%= simple_form_for [@astronaut, @booking] do |f| %>
            <%= f.input :date, as: :date, html5: true%>
            <%= f.submit "Meet Me!", class: "btn btn-primary m-3" %>
          <% end %>
        </div>
      </div>
      <h2 class="card-text text-center"><%= @astronaut.name %></h2>
      <p class="card-text"><%= @astronaut.bio %></p>
    </div>
    <div class="container row flex-row mt-3 p-3">
      <%= link_to 'Delete', astronaut_path, class:"btn btn- m-3 col-3", method: :delete %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card col flex-row mt-3 pb-3">
    <div class="d-flex flex-column justify-content-center mx-auto">
      <p class="text-center">You just booked:</p>
      <h1 class="text-center"> <%= @booking.astronaut.name %></h1>
  <% if @booking.astronaut.photo.attached?  %>
          <%= cl_image_tag @booking.astronaut.photo.key, height: 300, width: 400, crop: :fill, gravity: :face %>
        <% else  %>
          <img width="400" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.OrTvDaHqHaLr8GCNb25AngHaE8%26pid%3DApi&f=1" alt="">
        <% end  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstroApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="container">
          <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand">
          <img src="https://images.vexels.com/media/users/3/243737/isolated/lists/82beeb1d782c18e75144199b0c44939f-purple-space-rocket-stroke.png" alt="Astroapp logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
            </li>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1644356024/igs4icpkasbhkvalvzla.jpg" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
               <%= link_to "Add an astronaut", new_astronaut_path, class:"nav-link dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    </div>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>testtt</h2>
<p>testtstststst</p>